### ISSUE TITLE
Link für eine Anleitung

### ISSUE THREAD

**Issue by rstumpner** [rstumpner/pieces#8]
## Summary
- Wir würden für anfallende Anleitungen noch einen Link Anzeigen müssen der dann vom Handy aus direkt geklickt werden kann. 
- Um bei der Ausgabe schnell die Anleitung abrufen zu können wäre ein 2ter QR Code für die Anleitung gedacht 
- Wenn möglich über eine Variable im Javascript zum aktivieren oder deaktivieren

### Datenmodell
- neuer key:value mit `Anleitung`
```
{
    "id": 10,
    "Name der Chellange": "Lied gurgeln",
    "Beschreibung": "Gurgelt gemeinsam ein Lied",
    "Anzahl der Mitspieler": 2,
    "Dauer (Minuten)": 15,
    "Level": 3,
    "Schwerpunkt": "",
    "Kategorie": "",
    "Anleitung":"https://youtube.de",
    "Material": [],
    "Active": false
},

```

**Comment by Mxtthi** [comment]
Sind Schwerpunkt, Kategorie usw. für die Anzeige auf der Website auch relevant?
Dann würde ich sie noch hinzufügen

**Comment by rstumpner** [comment]
Nein , ist aktuell nicht relevant . War mal angedacht wird aber für das together 23 nicht benötigt.
