### ISSUE TITLE
Änderung Titel Aufzählung

### ISSUE THREAD

**Issue by rstumpner** [rstumpner/pieces#9]
## Summary
Ein kleiner grafischer Aufputz beim Titel der Aufgabe ein kleines puzzle icon in der Farbe des Levels einfügen. Im Link Anbei wären die Icons mit Level Farbe.

## Notizen
https://filesender.aco.net/?s=download&token=efbe4f2f-983a-43b4-ab13-3ee31b7e6717

**Comment by Mxtthi** [comment]
Download-Link funktioniert bei mir nicht

**Comment by rstumpner** [comment]
@Mxtthi Ich hab den Link erneuert , dieser ist abgelaufen . Sollte nun 15 Tage gültig sein

**Comment by rstumpner** [comment]
Farbcodes für die Aufgaben Levels:
• blau:  439daf
• gelb:  e0d326
• grün:  6cd571
• orange:  f59a2d

**Comment by Mxtthi** [comment]
Nummerierung ist 1-4, also von blau bis orange, hab ich das richtig verstanden?

**Comment by rstumpner** [comment]
Sozusagen ja . Es gibt die Basisfarbe und dann die 3 Levels . Wenn es möglich ist wären die Farbcodes als option einzutragen , dass wir diese leicht anpassen können wenn es notwendig ist.

**Comment by Mxtthi** [comment]
@rstumpner Könntest du das bitte noch genauer beschreiben wie ihr euch das vorstellt? Und wofür ist die Basisfarbe, hat nicht jede Challenge ein Level zugewiesen?

**Comment by rstumpner** [comment]
Danke für die Rückmeldung . Ich denke wir belassen es bei der Farbe der Icons
